### ISSUE TITLE
stack 脚手架设计讨论

### ISSUE THREAD

**Issue by outyua** [stack-labs/stack#77]
### 核心目标

> 让 stack 轻松快速上手, 方便管理stack应用

### 基本要点

1. 降低开发人员使用stack门槛, 做到代码生成和stack使用指引
2. 方便开发人员管理和查看项目运行情况

### 方案讨论

大家对脚手架有什么期望, 或者认为某个脚手架做的好的地方, 一起讨论下

**Comment by printfcoder** [comment]
- 标准的代码目录结构
   -  支持RPC
      - [todo目录结构]
      - DDD
      - MVC
   - 支持Web
       - [todo目录结构]
       - DDD
       - MVC

- 支持选择插件
  - 注册中心
  - 可选是否生成完整选项的配置文件

todo

**Comment by printfcoder** [comment]
先关闭，暂无人力实现
