### ISSUE TITLE
web 网关 模式

### ISSUE THREAD

**Issue by cashwar3** [stack-labs/stack#88]
可否提供一下，web作为网关的demo呢？
初始化传输模式为grpc是怎么处理的呢？

**Comment by printfcoder** [comment]
web作为网关？网关本身就是http的，把http向下转成rpc。

网关启动时transport=grpc即可，下游服务也一样启动方式。

**Comment by printfcoder** [comment]
参考：https://github.com/printfcoder/stack-rpc-tutorials/tree/master/examples/gateway/rpc

**Comment by printfcoder** [comment]
还有：https://github.com/printfcoder/stack-rpc-tutorials/tree/master/examples/deprecated/grpc

**Comment by cashwar3** [comment]
没有找到具体demo.
我的这边具体代码如下：
service := stack.NewWebService(...)
	if err := service.Init(); err != nil {
		panic(err)
	}
	
	/*
		转换为grpc
	*/
	//micro1.8版本：service.Options().Service.Init(micro.Transport(grpc.NewTransport()))
	//stack怎么转换呢？
	
	client := protoConfig.NewConfigService("go.micro.srv.exam", service.Client())

**Comment by printfcoder** [comment]
目前不支持web应用直接把transport替换成grpc的，可以另行声明一个客户端

```
	rpcClient := grpc.NewClient(
		client.Registry(s.Options().Registry),
		// ...
	)
	// 创建客户端
	greeter := proto.NewGreeterService("stack.rpc.greeter", rpcClient)
```

**Comment by cashwar3** [comment]
谢谢，舒大，我这边试一下

**Comment by cashwar3** [comment]
解决问题
