### ISSUE TITLE
请问 Transport 包的作用

### ISSUE THREAD

**Issue by yiippee** [stack-labs/stack#90]
舒大你好，感谢你的项目。
请教一个问题，框架中有一个Transport 包，代码注释说 Transport  is an interface which is used for communication between services. 但是client server 已经提供了services之间的通信了啊，为啥还需要 transport呢？似乎没感受它存在的意义。有相关例子阐述transport的用法和作用吗？
谢谢。

**Comment by printfcoder** [comment]
参考：
https://github.com/printfcoder/stack-rpc-tutorials/blob/master/others/share/learning-go/%E3%80%90%E7%AC%AC%E4%B8%80%E6%9C%9F%E3%80%91Go-Micro%E6%A1%86%E6%9E%B6%E8%AE%BE%E8%AE%A1.pptx

**Comment by yiippee** [comment]
谢谢你的回复，ppt中说transport是用于service间同步通信的，send 和 recv，但感觉与client server之间的通信没什么区别，比如基于grpc 的 client server也是可以stream来通信的。所以，transport有什么特别的作用吗？谢谢。
